<script lang="ts">
	import type { PageData, ActionData } from './$types';
	import Collage from '$lib/components/Collage.svelte';

	export let form: ActionData;
	export let data: PageData;

	const images = data?.images;
	const scenario = data?.scenario;
	const backgrounds = data?.backgrounds;
	const elements = data?.elements;
	const characters = data?.characters;

	const values = {
		collage: data?.json.collage?.future?.canvas || data?.json.collage?.present?.canvas || {},
		definition: data?.json.collage?.future?.definition || data?.json?.collage?.present?.definition || {}
	};

	$: stringifiedCollage = () => {
		return JSON.stringify(values.collage);
	}

	$: stringifiedDefinition = () => {
		return JSON.stringify(values.definition);
	}

	const resetCollage = () => {
		values.collage = data?.json.collage?.present?.canvas || {};
		values.definition = data?.json?.collage?.present?.definition || {};
	}

</script>

<div>
	<form method="POST" action="?/save" enctype="multipart/form-data">
		<div class="">
			<h4 class="h4">Collage</h4>
			<br />
			<span class="label space-y-4">
				
				<span>
					How might the friction, context and the character change in the future generated by your What If question? 
					Craft a visual representation about that future. Think of: 
					</span
				>
				<ul class="list">
					<li><span>🤔</span><span class="flex-auto">How might that future look like?</span></li>
					<li><span>🤖</span><span class="flex-auto">What are elements that emerge? Think of new characters, conversations, activities, and interactions.</span></li>
				</ul>								
				<!-- <ImageSelector scenario={scenario} images={images} values={values} input="collage" field="collage" upload="collageFile" extraClass="" /> -->
			</span>
			<br />
			<Collage {scenario} {backgrounds} {elements} {characters} bind:collage={values.collage} bind:definition={values.definition} />
			<input type="hidden" name="collage" value={stringifiedCollage()} />
			<input type="hidden" name="definition" value={stringifiedDefinition()} />
			<br />
			<a class="btn variant-ghost-warning" on:click={resetCollage}>Reset collage</a>
				
			<!-- <br />
			<h5 class="h5">Elements that emerge in this future: floating in the sky</h5>
			<br />
			<div class="w-full text-token grid grid-cols-1 md:grid-cols-3 gap-4">	
				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.floating} 
					input="floatingsprite1" field="sprite1" upload="floatingsprite1File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.floating} 
					input="floatingsprite2" field="sprite2" upload="floatingsprite2File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.floating} 
					input="floatingsprite3" field="sprite3" upload="floatingsprite3File" 
					extraClass="" />
			</div>
			<br />
			<h5 class="h5">Elements that emerge in this future: in the background</h5>
			<br />
			<div class="w-full text-token grid grid-cols-1 md:grid-cols-3 gap-4">	
				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.background} 
					input="backgroundsprite1" field="sprite1" upload="backgroundsprite1File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.background} 
					input="backgroundsprite2" field="sprite2" upload="backgroundsprite2File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.background} 
					input="backgroundsprite3" field="sprite3" upload="backgroundsprite3File" 
					extraClass="" />
			</div>
			<br />
			<h5 class="h5">Elements that emerge in this future: on the foreground</h5>
			<br />
			<div class="w-full text-token grid grid-cols-1 md:grid-cols-3 gap-4">	
				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.foreground} 
					input="foregroundsprite1" field="sprite1" upload="foregroundsprite1File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.foreground} 
					input="foregroundsprite2" field="sprite2" upload="foregroundsprite2File" 
					extraClass="" />

				<ImageSelector 
					scenario={scenario} 
					images={images} 
					values={values.elements.foreground} 
					input="foregroundsprite3" field="sprite3" upload="foregroundsprite3File" 
					extraClass="" />
			</div>


		</div> -->

		{#if values.definition?.characters?.length > 0}
		<div class="space-y-4">
			<br />
			<h4 class="h4">Characters</h4>			

			<!-- Actor 1 -->
			<div class="card">
				<!-- <header class="card-header">
					<b>{values.actor1.name ? values.actor1.name : 'Character 1'}</b>
				</header> -->
				<section class="p-4 space-y-4">

					<img src={values.definition.characters[0].url} alt="Character 1" width="100" />

					<label class="label space-y-4">
						<span>What's the name of this character?</span>
						<input
							bind:value={values.definition.characters[0].name}
							class="input"
							title="Name of the actor"
							type="text"
							name="actor1name"
						/>
					</label>

					<label class="label">
						<span>What does this character say, think, feel?</span>
						<textarea
							bind:value={values.definition.characters[0].statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor1statement"
						/>
					</label>
				</section>
			</div>
			

			<!-- Actor 2 -->
			{#if values.definition.characters?.length > 1}			
			<div class="card">
				<!-- <header class="card-header">
					<b>{values.actor2.name ? values.actor2.name : 'Character 2'}</b>
				</header> -->
				<section class="p-4 space-y-4">

					<img src={values.definition.characters[1].url} alt="Character 2" width="100" />

					<label class="label space-y-4">
						<span>What's the name of this character?</span>
						<input
							bind:value={values.definition.characters[1].name}
							class="input"
							title="Name of the actor"
							type="text"
							name="actor2name"
						/>
					</label>

					<label class="label">
						<span>What does this actor say, think, feel?</span>
						<textarea
							bind:value={values.definition.characters[1].statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor2statement"
						/>
					</label>
				</section>
			</div>
			{/if}

			<!-- Actor 3 -->
			{#if values.definition.characters?.length > 2}			
			<div class="card">
				<!-- <header class="card-header">
					<b>{values.actor3.name ? values.actor3.name : 'Character 3'}</b>
				</header> -->
				<section class="p-4 space-y-4">				

					<img src={values.definition.characters[2].url} alt="Character 3" width="100" />

					<label class="label space-y-4">
						<span>What's the name of this character?</span>
						<input
							bind:value={values.definition.characters[2].name}
							class="input"
							title="Name of the actor"
							type="text"
							name="actor3name"
						/>
					</label>

					<label class="label">
						<span>What does this actor say, think, feel?</span>
						<textarea
							bind:value={values.definition.characters[2].statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor3statement"
						/>
					</label>
				</section>
			</div>
			{/if}

		</div>
		{/if}

		<br />
		<button class="btn variant-filled-primary">Save</button>
		&nbsp;&nbsp;&nbsp;&nbsp; 
		<button class="btn variant-filled-primary" formaction="?/previous">Back</button>		
		<button class="btn variant-filled-primary" formaction="?/next">Next</button>
	</form>
</div>
