<script lang="ts">
	import type { PageData, ActionData } from './$types';
	import ImageSelector from '$lib/components/ImageSelector.svelte';

	export let form: ActionData;
	export let data: PageData;

	const images = data?.images;
	const scenario = data?.scenario;

	const values = {
		collage: form?.collage || data?.json.friction.options.a.alternativeBackground || data?.json.scene.background || '',
		actor1: {
			name: form?.actor1.name || data?.json.actors[0].description || '',
			statement: form?.actor1.statement || data?.json.actors[0].content.after.a || '',
			// avatar: form?.actor1.avatar || data?.json.actors[0].avatar || '',
			// sprite: form?.actor1.sprite || data?.json.actors[0].sprite || ''
		},
		actor2: {
			name: form?.actor2.name || data?.json.actors[1].description || '',
			statement: form?.actor2.statement || data?.json.actors[1].content.after.a || '',
			// avatar: form?.actor2.avatar || data?.json.actors[1].avatar || '',
			// sprite: form?.actor2.sprite || data?.json.actors[1].sprite || ''
		},
		actor3: {
			name: form?.actor3.name || data?.json.actors[2].description || '',
			statement: form?.actor3.statement || data?.json.actors[2].content.after.a || '',
			// avatar: form?.actor3.avatar || data?.json.actors[2].avatar || '',
			// sprite: form?.actor3.sprite || data?.json.actors[2].sprite || ''
		},		
	};
</script>

<div>
	<form method="POST" action="?/save" enctype="multipart/form-data">
		<div class="">
			<h4 class="h4">Collage</h4>
			<br />
			<span class="label space-y-4">
				
				<span>
					How might the friction, context and the character change in the future generated by your What If question? 
					Craft a visual representation about that future. Think of: 
					</span
				>
				<ul class="list">
					<li><span>🤔</span><span class="flex-auto">How might that future look like?</span></li>
					<li><span>🤖</span><span class="flex-auto">What are elements that emerge? Think of new characters, conversations, activities, and interactions.</span></li>
				</ul>				

				<ImageSelector scenario={scenario} images={images} values={values} input="collage" field="collage" upload="collageFile" extraClass="" />
			</span>
		</div>

		<div class="space-y-4">
			<br />
			<h4 class="h4">Characters</h4>			
			<!-- Actor 1 -->
			<div class="card">
				<header class="card-header"><b>{values.actor1.name}</b></header>
				<section class="p-4 space-y-4">

					<label class="label">
						<span>What does this character say, think, feel about this future?</span>
						<textarea
							value={values.actor1.statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor1statement"
						/>
					</label>
				</section>
			</div>

			<!-- Actor 2 -->
			<div class="card">
				<header class="card-header"><b>{values.actor2.name}</b></header>
				<section class="p-4 space-y-4">
					<label class="label">
						<span>What does this character say, think, feel about this future?</span>
						<textarea
							value={values.actor2.statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor2statement"
						/>
					</label>
				</section>
			</div>

			<!-- Actor 3 -->
			<div class="card">
				<header class="card-header"><b>{values.actor3.name}</b></header>
				<section class="p-4 space-y-4">
					<label class="label">
						<span>What does this character say, think, feel about this future?</span>
						<textarea
							value={values.actor3.statement}
							class="textarea"
							title="Actor statement"
							rows="3"
							name="actor3statement"
						/>
					</label>
				</section>
			</div>		
		</div>

		<br />
		<button class="btn variant-filled-primary">Save</button>
		&nbsp;&nbsp;&nbsp;&nbsp; 
		<button class="btn variant-filled-primary" formaction="?/previous">Back</button>		
		<button class="btn variant-filled-primary" formaction="?/next">Next</button>
	</form>
</div>
