<script lang="ts">
	import type { PageData, ActionData } from './$types';
	import Collage from '$lib/components/Collage.svelte';

	export let form: ActionData;
	export let data: PageData;

	const images = data?.images;
	const scenario = data?.scenario;
	const backgrounds = data?.backgrounds;
	const elements = data?.elements;
	const characters = data?.characters;

	const values = {
		collage: data?.json.collage?.future?.canvas || data?.json.collage?.present?.canvas || {},
		definition: data?.json.collage?.future?.definition || data?.json?.collage?.present?.definition || {},
		file: undefined
	};

	$: stringifiedCollage = () => {
		return JSON.stringify(values.collage);
	}

	$: stringifiedDefinition = () => {
		return JSON.stringify(values.definition);
	}

	const resetCollage = () => {
		values.collage = data?.json.collage?.present?.canvas || {};
		values.definition = data?.json?.collage?.present?.definition || {};
	}

	const handleSubmit = async () => {
		console.log('Submitting');
		if (values.file) {
			let fileInputElement = document.getElementById('file');		
			let container = new DataTransfer();
			container.items.add(values.file);
			fileInputElement.files = container.files;
		}
	}

</script>

<div>
	<form method="POST" on:submit={handleSubmit} action="?/save" enctype="multipart/form-data">
		<div class="">
			<h4 class="h4">Collage</h4>
			<br />
			<span class="label space-y-4">
				
				<span>
					How might the friction, context and the character change in the future generated by your What If question? 
					Craft a visual representation about that future. Think of: 
					</span
				>
				<ul class="list">
					<li><span>🤔</span><span class="flex-auto">How might that future look like?</span></li>
					<li><span>🤖</span><span class="flex-auto">What are elements that emerge? Think of new characters, conversations, activities, and interactions.</span></li>
				</ul>								
				<!-- <ImageSelector scenario={scenario} images={images} values={values} input="collage" field="collage" upload="collageFile" extraClass="" /> -->
			</span>
			<br />
			<Collage {scenario} {backgrounds} {elements} {characters} bind:collage={values.collage} bind:definition={values.definition} bind:file={values.file} />
			<input type="hidden" name="collage" value={stringifiedCollage()} />
			<input type="hidden" name="definition" value={stringifiedDefinition()} />
			<input id="file" type="file" name="collageFile" bind:value={values.file} />
			<br />
			<a class="btn variant-ghost-warning" on:click={resetCollage}>Reset collage</a>			
		</div> 

		<div class="space-y-4">
			<br />
			<h4 class="h4">Characters</h4>			

			{#each (values.definition.characters || []) as character, i}
				<div class="card">
					<header class="card-header">
						<img src={character.url} alt={`Character ${i}`} width="100" />
					</header>
					<section class="p-4 space-y-4">
						<label class="label space-y-4">
							<span>What's the name of this character?</span>
							<input
								bind:value={character.name}
								class="input"
								title="Name of the actor"
								type="text"
								name="actor1name"
							/>
						</label>

						<label class="label">
							<span>What does this character say, think, feel?</span>
							<textarea
								bind:value={character.statement}
								class="textarea"
								title="Actor statement"
								rows="3"
								name="actor1statement"
							/>
						</label>
					</section>
				</div>
			{/each}

		</div>

		<br />
		<button class="btn variant-filled-primary">Save</button>
		&nbsp;&nbsp;&nbsp;&nbsp; 
		<button class="btn variant-filled-primary" formaction="?/previous">Back</button>		
		<button class="btn variant-filled-primary" formaction="?/next">Next</button>
	</form>
</div>

<style>
	input#file {
		display: none;
	}
</style>
